merge_base_with = "origin/main"

[[linter]]
code = 'PYLINT'
include_patterns = ['**/*.py']
exclude_patterns = [
    'submodules/**',
    '**/submodules/**',
    'tico/utils/mx/**',
]
command = [
    'lintrunner_adapters',
    'run',
    'pylint_linter',
    '--',
    '--rcfile=.pylintrc',
    '--job=0',
    '@{{PATHSFILE}}'
]
init_command = [
    'lintrunner_adapters',
    'run',
    'pip_init',
    '--dry-run={{DRYRUN}}',
    '--requirement=requirements-lintrunner.txt',
]

# Black + usort
[[linter]]
code = 'UFMT'
include_patterns = [
    '**/*.py',
    '**/*.pyi',
]
exclude_patterns = [
    'submodules/**',
    '**/submodules/**',
    'tico/utils/mx/**',
]
command = [
    'lintrunner_adapters',
    'run',
    'ufmt_linter',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'lintrunner_adapters',
    'run',
    'pip_init',
    '--dry-run={{DRYRUN}}',
    '--no-black-binary',
    '--requirement=requirements-lintrunner.txt',
]
is_formatter = true

[[linter]]
code = 'MYPY'
include_patterns = [
    '**/*.py',
    '**/*.pyi',
]
exclude_patterns = [
    'submodules/**',
    '**/submodules/**',
    'old/**',
    'tico/utils/mx/**',
]
command = [
    'lintrunner_adapters',
    'run',
    'mypy_linter',
    '--config=mypy.ini',
    '--show-notes',
    '--show-disable',
    '--',
    '@{{PATHSFILE}}',
]
init_command = [
    'lintrunner_adapters',
    'run',
    'pip_init',
    '--dry-run={{DRYRUN}}',
    '--requirement=requirements-lintrunner.txt',
]
