name: Check Workflows
description: Formats and validates workflow .yaml files.

on:
  pull_request:
    paths:
      # WARNING: PRs from forked repo are not allowed.
      - '.github/workflows/**'

jobs:
  actionlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - run: mkdir /CODE/lint -p
      - name: Run actionlint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) 1.7.7
          ./actionlint -color -verbose
        shell: bash
